version: '3.9'

services:
  # Servicio para el backend (Django)
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: >
      sh -c "./wait-for-it.sh db:5432 -- python manage.py runserver 0.0.0.0:8000"
    volumes:
      - ./backend:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    env_file:
      - .env
    environment:
      DB_HOST: db
      DB_NAME: ${POSTGRES_DB}
      DB_USER: ${POSTGRES_USER}
      DB_PASSWORD: ${POSTGRES_PASSWORD}
      DEBUG: "True"

  # Servicio para PostgreSQL
  db:
    image: postgres:15
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports :
      - "5432:5432"
  # Servicio para el frontend (Vue.js)
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    depends_on:
      - backend
    environment:
      VUE_APP_API_URL: http://localhost:8000  # URL del backend para Vue.js

volumes:
  postgres_data: